services:
  - type: web
    name: himafor-backend
    env: docker
    plan: free
    region: singapore
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres.yywpabmofygfgyxyxggn
      - key: SPRING_DATASOURCE_PASSWORD
        value: anakbaik11122
      - key: APP_JWT_SECRET
        value: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
